package gradebook;
// Generated Feb 22, 2017 3:30:16 PM by Hibernate Tools 4.3.1



/**
 * GradebookAssignment generated by hbm2java
 */
public class GradebookAssignment  implements java.io.Serializable {


     private Integer gradebookAssignmentId;
     private Assignment assignment;
     private Gradebook gradebook;

    public GradebookAssignment() {
    }

    public GradebookAssignment(Assignment assignment, Gradebook gradebook) {
       this.assignment = assignment;
       this.gradebook = gradebook;
    }
   
    public Integer getGradebookAssignmentId() {
        return this.gradebookAssignmentId;
    }
    
    public void setGradebookAssignmentId(Integer gradebookAssignmentId) {
        this.gradebookAssignmentId = gradebookAssignmentId;
    }
    public Assignment getAssignment() {
        return this.assignment;
    }
    
    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }
    public Gradebook getGradebook() {
        return this.gradebook;
    }
    
    public void setGradebook(Gradebook gradebook) {
        this.gradebook = gradebook;
    }




}


