package gradebook;
// Generated Feb 22, 2017 3:30:16 PM by Hibernate Tools 4.3.1



/**
 * GradebookStudent generated by hbm2java
 */
public class GradebookStudent  implements java.io.Serializable {


     private Integer gradebookStudentId;
     private Gradebook gradebook;
     private Student student;

    public GradebookStudent() {
    }

    public GradebookStudent(Gradebook gradebook, Student student) {
       this.gradebook = gradebook;
       this.student = student;
    }
   
    public Integer getGradebookStudentId() {
        return this.gradebookStudentId;
    }
    
    public void setGradebookStudentId(Integer gradebookStudentId) {
        this.gradebookStudentId = gradebookStudentId;
    }
    public Gradebook getGradebook() {
        return this.gradebook;
    }
    
    public void setGradebook(Gradebook gradebook) {
        this.gradebook = gradebook;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


