package gradebook;
// Generated Feb 22, 2017 3:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private Integer instructorId;
     private String instructorEmail;
     private Set<Gradebook> gradebooks = new HashSet<>(0);

    public Instructor() {
    }

	
    public Instructor(String instructorEmail) {
        this.instructorEmail = instructorEmail;
    }
    public Instructor(String instructorEmail, Set<Gradebook> gradebooks) {
       this.instructorEmail = instructorEmail;
       this.gradebooks = gradebooks;
    }
   
    public Integer getInstructorId() {
        return this.instructorId;
    }
    
    public void setInstructorId(Integer instructorId) {
        this.instructorId = instructorId;
    }
    public String getInstructorEmail() {
        return this.instructorEmail;
    }
    
    public void setInstructorEmail(String instructorEmail) {
        this.instructorEmail = instructorEmail;
    }
    public Set<Gradebook> getGradebooks() {
        return this.gradebooks;
    }
    
    public void setGradebooks(Set<Gradebook> gradebooks) {
        this.gradebooks = gradebooks;
    }




}


