package gradebook;
// Generated Feb 22, 2017 3:30:16 PM by Hibernate Tools 4.3.1



/**
 * SemesterCourse generated by hbm2java
 */
public class SemesterCourse  implements java.io.Serializable {


     private Integer semesterCourseId;
     private Course course;
     private Semester semester;

    public SemesterCourse() {
    }

    public SemesterCourse(Course course, Semester semester) {
       this.course = course;
       this.semester = semester;
    }
   
    public Integer getSemesterCourseId() {
        return this.semesterCourseId;
    }
    
    public void setSemesterCourseId(Integer semesterCourseId) {
        this.semesterCourseId = semesterCourseId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }




}


