package gradebook;
// Generated Feb 22, 2017 3:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Semester generated by hbm2java
 */
public class Semester  implements java.io.Serializable {


     private Integer semesterId;
     private String semesterName;
     private Set<Gradebook> gradebooks = new HashSet<Gradebook>(0);
     private Set<SemesterCourse> semesterCourses = new HashSet<SemesterCourse>(0);

    public Semester() {
    }

	
    public Semester(String semesterName) {
        this.semesterName = semesterName;
    }
    public Semester(String semesterName, Set<Gradebook> gradebooks, Set<SemesterCourse> semesterCourses) {
       this.semesterName = semesterName;
       this.gradebooks = gradebooks;
       this.semesterCourses = semesterCourses;
    }
   
    public Integer getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(Integer semesterId) {
        this.semesterId = semesterId;
    }
    public String getSemesterName() {
        return this.semesterName;
    }
    
    public void setSemesterName(String semesterName) {
        this.semesterName = semesterName;
    }
    public Set<Gradebook> getGradebooks() {
        return this.gradebooks;
    }
    
    public void setGradebooks(Set<Gradebook> gradebooks) {
        this.gradebooks = gradebooks;
    }
    public Set<SemesterCourse> getSemesterCourses() {
        return this.semesterCourses;
    }
    
    public void setSemesterCourses(Set<SemesterCourse> semesterCourses) {
        this.semesterCourses = semesterCourses;
    }




}


