package gradebook;
// Generated Feb 22, 2017 3:30:16 PM by Hibernate Tools 4.3.1



/**
 * StudentAssignment generated by hbm2java
 */
public class StudentAssignment  implements java.io.Serializable {


     private Integer studentAssignmentId;
     private Assignment assignment;
     private Student student;
     private int studentAssignmentGrade;

    public StudentAssignment() {
    }

    public StudentAssignment(Assignment assignment, Student student, int studentAssignmentGrade) {
       this.assignment = assignment;
       this.student = student;
       this.studentAssignmentGrade = studentAssignmentGrade;
    }
   
    public Integer getStudentAssignmentId() {
        return this.studentAssignmentId;
    }
    
    public void setStudentAssignmentId(Integer studentAssignmentId) {
        this.studentAssignmentId = studentAssignmentId;
    }
    public Assignment getAssignment() {
        return this.assignment;
    }
    
    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public int getStudentAssignmentGrade() {
        return this.studentAssignmentGrade;
    }
    
    public void setStudentAssignmentGrade(int studentAssignmentGrade) {
        this.studentAssignmentGrade = studentAssignmentGrade;
    }




}


