package gradebook;
// Generated Feb 22, 2017 3:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer studentId;
     private String studentFname;
     private String studentLname;
     private Set<StudentAssignment> studentAssignments = new HashSet<StudentAssignment>(0);
     private Set<GradebookStudent> gradebookStudents = new HashSet<GradebookStudent>(0);

    public Student() {
    }

	
    public Student(String studentFname, String studentLname) {
        this.studentFname = studentFname;
        this.studentLname = studentLname;
    }
    public Student(String studentFname, String studentLname, Set<StudentAssignment> studentAssignments, Set<GradebookStudent> gradebookStudents) {
       this.studentFname = studentFname;
       this.studentLname = studentLname;
       this.studentAssignments = studentAssignments;
       this.gradebookStudents = gradebookStudents;
    }
   
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public String getStudentFname() {
        return this.studentFname;
    }
    
    public void setStudentFname(String studentFname) {
        this.studentFname = studentFname;
    }
    public String getStudentLname() {
        return this.studentLname;
    }
    
    public void setStudentLname(String studentLname) {
        this.studentLname = studentLname;
    }
    public Set<StudentAssignment> getStudentAssignments() {
        return this.studentAssignments;
    }
    
    public void setStudentAssignments(Set<StudentAssignment> studentAssignments) {
        this.studentAssignments = studentAssignments;
    }
    public Set<GradebookStudent> getGradebookStudents() {
        return this.gradebookStudents;
    }
    
    public void setGradebookStudents(Set<GradebookStudent> gradebookStudents) {
        this.gradebookStudents = gradebookStudents;
    }




}


