package gradebook;
// Generated Feb 22, 2017 3:30:16 PM by Hibernate Tools 4.3.1



/**
 * StudentAssignment generated by hbm2java
 */
public class StudentAssignment  implements java.io.Serializable {


     private Integer studentAssignmentId;
     private GradebookAssignment assignment;
     private Student student;
     private Integer gradebookAssignmentId;
     private Integer studentAssignmentGrade;

    public StudentAssignment() {
    }

    public StudentAssignment(GradebookAssignment assignment, Student student, int studentAssignmentGrade) {
       this.assignment = assignment;
       this.student = student;
       this.studentAssignmentGrade = studentAssignmentGrade;
    }
   
    public Integer getStudentAssignmentId() {
        return this.studentAssignmentId;
    }
    
    public void setStudentAssignmentId(Integer studentAssignmentId) {
        this.studentAssignmentId = studentAssignmentId;
    }
    public GradebookAssignment getAssignment() {
        return this.assignment;
    }
    
    public void setAssignment(GradebookAssignment assignment) {
        this.assignment = assignment;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Integer getStudentAssignmentGrade() {
        return this.studentAssignmentGrade;
    }
    
    public void setStudentAssignmentGrade(Integer studentAssignmentGrade) {
        this.studentAssignmentGrade = studentAssignmentGrade;
    }

    public Integer getGradebookAssignmentId() {
        return gradebookAssignmentId;
    }

    public void setGradebookAssignmentId(Integer gradebookAssignmentId) {
        this.gradebookAssignmentId = gradebookAssignmentId;
    }

    
}


